#!/bin/bash

clear
read -p "How many minutes and seconds? " minutes seconds
clear
echo "Timer started"

sleep ${seconds}s

minutesConsumed=0
while [[ "$minutesConsumed" -ne "$minutes" ]]; do
	sleep 1m
	clear
	minutesConsumed=$((minutesConsumed + 1))
	echo "Timer started"
	echo "Remain: $((minutes-minutesConsumed)) minutes"
done

clear
echo "Timer ended"
# if headphones are unpluged (https://askubuntu.com/questions/133809/mute-sound-on-headphone-unplug)
if [[ "$(cat '/proc/asound/card0/codec#0' | head -n 140 | tail -n 1 | grep -Po 'OUT')" == "OUT" ]]; then
	mpv ~/Música/bash/timer.mp3 &> /dev/null &
else
	mpv --volume 50 ~/Música/bash/timer.mp3 &> /dev/null &
fi

read -p "Press enter to finish -> "
kill $!
