#!/bin/bash

# It is neccesary acpid

if [[ "$(ps aux | grep -P acpi_listen | grep -Pv 'grep')" == "" ]]; then
	systemctl start acpid.service
	acpi_listen | grep -Pi 'headphone' > ~/tmp/headphonesStatus &
fi

playMusic () {
	if [[ "$(cat ~/tmp/headphonesStatus | tail -n 1 | grep -P 'unplug')" != "" ]]; then
		mpv ~/Música/bash/timer.mp3 &> /dev/null &
	else
		mpv --volume 50 ~/Música/bash/timer.mp3 &> /dev/null &
	fi
}

clear
read -p "How many minutes and seconds? " minutes seconds
clear
echo "Timer started"

sleep ${seconds}s

minutesConsumed=0
while [[ "$minutesConsumed" -ne "$minutes" ]]; do
	sleep 1m
	clear
	minutesConsumed=$((minutesConsumed + 1))
	echo "Timer started"
	echo "Remain: $((minutes-minutesConsumed)) minutes"
done

clear
echo "Timer ended"
playMusic

read -p "Press enter to finish -> "
kill $!
